dzj/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('qapp/', include(('qapp.urls', 'qapp'), namespace='qapp')),
    path('admin/', admin.site.urls),
    # Redirect root to app
    path('', RedirectView.as_view(pattern_name='qapp:index'))
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/login/$',
        auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"
        ),
    url(r'^accounts/logout/$',
        auth_views.LogoutView.as_view(template_name="registration/logged_out.html"), name="logout"
        ),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

qapp/urls.py
from . import views
from django.conf.urls import url

"""
For using one generic.ListView for all type of gates, is necessary to specify parameter gate_type in as_view method.
This parameter will be provided to Class GateListView in views.py and available in each method of this class.
"""

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bjc$', views.GateListView.as_view(gate_type='bjc'), name='bjc_list'),
    url(r'^bjw$', views.GateListView.as_view(gate_type='bjw'), name='bjw_list'),
    url(r'^ikw$', views.GateListView.as_view(gate_type='ikw'), name='ikw_list'),
    url(r'^ikk$', views.GateListView.as_view(gate_type='ikk'), name='ikk_list'),
    url(r'^(?P<pk>[\w-]+)/$', views.DetailView.as_view(), name='gate_details'),
    url(r'^(?P<pk>[\w-]+)/update$', views.gate_update, name='update'),
    url(r'^(?P<pk>[\w-]+)/log$', views.LogView.as_view(), name='log'),
    url(r'^add$', views.gate_add, name='gate_add'),
    url(r'^(?P<pk>[\w-]+)/edit$', views.gate_edit, name='edit'),
    url(r'^mygates$', views.MyGates.as_view(), name='my_gates'),
    url(r'^massupdate$', views.mass_update, name='mass_update'),
    url(
        r'^csm/(?P<car>\D\d)/(?P<operation_no>\D{2}\d{4})$',
        views.gate_change_status_mobile,
        name='gate_change_status_mobile'
    )

]

qapp/views.py
from .models import Gate, Tram
from .filters import GateFilter
from django.views import generic
from django.utils import timezone
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.core.validators import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import (GateAddForm, GateFileAddFormSet, CommentAddForm, CommentFileAddFormSet, GateChangeForm,
                    GateFileChangeFormSet, GateChangeStatusMobile)


def is_dzj_member(user):

    # Test for decorator
    return user.groups.filter(name='dzj').exists()


def log_date_time(**kwargs):

    if kwargs == {'format': 'yes'}:
        return timezone.now().strftime("%Y-%m-%d %H:%M:%S.%f")
    else:
        return timezone.now()


def generate_log(curr_user, pk, log_dict, gate, category, action, *args):

    """Function generate logs for changes in gate object:

    :param curr_user: user, that make changes in gate object (request.user),
    :param pk: primary key of gate - for printing on screen (identification of gate in 'results.html'),
    :param log_dict: name of dictionary with messages (defined in a view),
    :param gate: gate, for which log was generated,
    :param category: 'S' (sucess) or 'E' (error),
    :param action: type of action to log; value from act_type dictionary,
    :param args: optional argument with for example new value (see act_type dictionary)
    """

    if args:
        new_value = args[0]
    else:
        new_value = ''

    curr_time = timezone.now().strftime("%Y-%m-%d %H:%M:%S:%f")

    act_type = {
        'rating': u'zaktualizowano ocenę: {}'.format(new_value),
        'status': u'zaktualizowano status: {}'.format(new_value),
        'comment': u'dodano komentarz',
        'file': u'dodano plik',
        'newgate': u'utworzono bramkę',
        'editgate': u'zmieniono bramkę'
    }

    gate.log_set.create(
        date_time=log_date_time(),
        author=curr_user,
        category=category,
        action=act_type[action],
    )

    # Add recently added log to view's log dictionary to show them as result (see view's 'redirect' - to 'result.html').
    log_dict[curr_time] = [pk, category, act_type[action]]


def change_rating(gate, value):

    """Function change gate rating (after marking gate.status == 'O').
    If value is 'OK', status will be set to 'A' (gate is closed, so can be moved to archive; prevents from changes)
    and rating to 'OK'.
    If rating is 'NOK', status will be se to 'P', rejection counter (how many times inspection was performed) will
    be increased by 1, and rating will be set to 'NOK' (gate have to be fixed, and inspected once again).

    :param gate: gate object, which will be changed,
    :param value: 'OK' when gate could be accepted, 'P' if gate have to be corrected.
    """

    if value == 'OK':
        status = 'A'
        gate.status = status
        gate.rating = value
    else:
        status = 'P'
        gate.status = status
        gate.reject_counter += 1
        gate.rating = value
    gate.save()


def change_status(gate, value):

    """Function change gate status (gate.status can be set as 'O' for receive an rating).
    Allow to change gate status to 'O' (ready to inspection). After set this status, rating is cleaned.

    :param gate: gate object, which will be changed,
    :param value: usually 'O'.
    """

    gate.status = value
    gate.rating = ''
    gate.save()


def index(request):
    return render(request, 'qapp/gate/index.html', )


class GateListView(generic.ListView):

    """Universal ListView for all types of Gate object.
    Necessary to specify Gate.type in parameters delivered to class (see urls.py for app).
    For keeping compatibility with django-filter addon, methods get_queryset and get_context_data had to be override.
    (filtered data instead original queryset result have to be delivered to template).
    Due to many Gate.type variants, also ordering should be customized (Gate.type == 'BJW' had no
    tram and car attributes (they are NULL)).
    """

    queryset = None
    gate_type = None
    template_name = 'qapp/gate/list.html'
    context_object_name = 'gate_list'
    paginate_by = 20

    def get_queryset(self):
        # Type is stored in database as big-letter word, so 'bjc' != 'BJC'.
        if self.gate_type.upper() == 'BJW':
            ordering = ['bogie']
        else:
            ordering = ['tram', 'car']
        queryset = Gate.objects.filter(type=self.gate_type.upper()).order_by(*ordering)
        self.gate_list = GateFilter(self.request.GET, queryset=queryset)
        return self.gate_list.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super(GateListView, self).get_context_data(**kwargs)
        # Return Gate.type to template.
        context['gate_type'] = self.gate_type
        # Return object (for generating form) to template.
        context['gate_list_filter'] = self.gate_list
        return context


class DetailView(generic.DetailView):

    model = Gate
    template_name = 'qapp/gate/details.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Gate, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['comment_form'] = CommentAddForm(None)
        context['comment_formset'] = CommentFileAddFormSet(None)
        return context


@login_required
def gate_update(request, pk):

    log_messages = {}
    gate = get_object_or_404(Gate, pk=pk)
    if request.method == "POST":
        comment_form = CommentAddForm(request.POST)
        comment_formset = CommentFileAddFormSet(request.POST, request.FILES)
        if comment_form.is_valid() and comment_formset.is_valid():
            try:
                # Check, does it is change of Gate.rating or Gate.status?
                change_rating(gate, request.POST['new_rating'])
                generate_log(request.user, pk, log_messages, gate, 'S', 'rating', request.POST['new_rating'])
            except KeyError:
                change_status(gate, request.POST['new_status'])
                generate_log(request.user, pk, log_messages, gate, 'S', 'status', request.POST['new_status'])
            if comment_form.has_changed():
                # If comment-text is not empty, add Comment object.
                try:
                    comment = comment_form.save(commit=False)
                    comment.id = None
                    comment.author = request.user
                    comment.com_rel_gate = gate
                    comment.date_time = log_date_time()
                    comment.save()
                    generate_log(request.user, pk, log_messages, gate, 'S', 'comment')
                    # Try to iterate over files attached to Comment object and add every file as CommentFile object.
                    # Adding empty comment-text with files is prevented, using JS (see details.html template).
                    for form in comment_formset:
                        if form.is_valid():
                            if form.has_changed():
                                a = form.save(commit=False)
                                a.id = None
                                a.file_rel_comment = comment
                                a.save()
                                generate_log(request.user, pk, log_messages, gate, 'S', 'file')
                except IntegrityError:
                    log_messages[log_date_time(format='yes')] = [pk, 'E', u'Bramka nie została zaktualizowana']
            log_messages[log_date_time(format='yes')] = [pk, 'S', u'Bramka została zaktualizowana']
            # If all jobs finished, go to result page and show the changes stored in log_messages dict
            return render(request, 'qapp/gate/results.html', {
                'log_messages': log_messages,
            }
                          )
        else:
            # If there some errors in form, allow user to correct data (render pre-filled form with error messages).
            gate_form = GateAddForm(request.POST)
            gate_formset = GateFileAddFormSet(request.POST)
            return render(request, 'qapp/gate/add.html', {
                'gate_form': gate_form,
                'formset': gate_formset,
            }
                          )
    else:
        # If request was not made by POST method, render blank form.
        gate_form = GateAddForm(None)
        gate_formset = GateFileAddFormSet(None)
        return render(request, 'qapp/gate/add.html', {
            'gate_form': gate_form,
            'formset': gate_formset,
        }
                      )


@login_required
def gate_change_status_mobile(request, car, operation_no):

    log_messages = {}
    car = car.upper()
    operation_no = operation_no.upper()
    if request.method == 'POST':
        gate_form = GateChangeStatusMobile(request.POST)
        if gate_form.is_valid():
            tram = Tram.objects.get(pk=gate_form.cleaned_data['tram'])
            car = gate_form.cleaned_data['car']
            operation_no = gate_form.cleaned_data['operation_no']
            gate = get_object_or_404(Gate, tram=tram.pk, car=car, operation_no=operation_no)
            if gate.status == 'O':
                return HttpResponse(
                    'Bramka <b>{} {}</b> <i>(id {})</i> na <b>{}</b>, <b>{}</b> oczekuje już na ocenę DZJ!'.format(
                        operation_no,
                        gate.name,
                        gate.id,
                        tram,
                        car,
                    )
                )
            gate.status = 'O'
            gate.save()
            # Catch log and store in related to Gate, GateLog object.

qapp/templates/qapp/base.html
<!DOCTYPE html>
{% load user_tags %}
<html lang="pl">
<head>
    {% load static %}
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="header">
        <h1>QAPP</h1>
    </div>
    <div class="navbar">
        <a class="leftlink" href="{% url 'qapp:index' %}">Strona główna</a>
        <a class="leftlink" href="{% url 'qapp:bjc_list' %}">BJ Człony</a>
        <a class="leftlink" href="{% url 'qapp:bjw_list' %}">BJ Wózki</a>
        <a class="leftlink" href="{% url 'qapp:ikw_list' %}">IK Wewnętrzna</a>
        <a class="leftlink" href="{% url 'qapp:ikk_list' %}">IK Klient</a>
        {% if request.user.is_authenticated %}
        {% if request.user|dzj_member %}
        <a class="leftlink" href="{% url 'qapp:gate_add' %}">Dodaj bramkę</a>
        {% endif %}
        <a class="leftlink" href="{% url 'qapp:my_gates' %}">Moje bramki</a>
        <div class="dropdown">
            <button class="dropbtn">{{ request.user.last_name }} {{ request.user.first_name }} ({{ request.user.username }})</button>
            <div class="dropdown-content">
                {% if request.user|dzj_member %}
                <a href="{% url 'qapp:my_gates' %}?operation_no=&status=O">Do oceny: {{ user_gates_count }}</a>
                {% else %}
                <a href="{% url 'qapp:my_gates' %}?operation_no=&status=P">Do poprawki: {{ user_gates_count }}</a>
                {% endif %}
                <a href="{% url 'logout' %}?next={% url 'qapp:index' %}">Wyloguj</a>
            </div>
        </div>
        {% else %}
        <a href="{% url 'login' %}?next={% url 'qapp:index' %}" style="float:right">Zaloguj</a>
        {% endif %}
    </div>
    <div class="row">
        <div class="leftcolumn">
            {% block content %}
            {% endblock %}
        </div>
        <div class="rightcolumn">
            <div class="card" id="first_card">
                {% block firstcard %}
                {% endblock %}
            </div>
            <div class="card" id="second_card">
                <h3>Najwięcej odrzuceń</h3>
                <hr>
                <ol>
                    {% for gate in top_five %}
                    <li><a href="{{ gate.get_absolute_url}}">{{ gate.name }}<br>(ilość odrzuceń: {{ gate.reject_counter }})</a></li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
    <div class="footer">
        <img src="{% static 'img/python_powered.png' %}"><img src="{% static 'img/and_ed.png' %}"><img src="{% static 'img/django_powered.png' %}">
    </div>
    <script src="https://cdn.jsdelivr.net/npm/screw-filereader@1.4.3/index.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>