dzj/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('qapp/', include(('qapp.urls', 'qapp'), namespace='qapp')),
    path('admin/', admin.site.urls),
    # Redirect root to app
    path('', RedirectView.as_view(pattern_name='qapp:index'))
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/login/$',
        auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"
        ),
    url(r'^accounts/logout/$',
        auth_views.LogoutView.as_view(template_name="registration/logged_out.html"), name="logout"
        ),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

qapp/urls.py
from . import views
from django.conf.urls import url

"""
For using one generic.ListView for all type of gates, is necessary to specify parameter gate_type in as_view method.
This parameter will be provided to Class GateListView in views.py and available in each method of this class.
"""

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bjc$', views.GateListView.as_view(gate_type='bjc'), name='bjc_list'),
    url(r'^bjw$', views.GateListView.as_view(gate_type='bjw'), name='bjw_list'),
    url(r'^ikw$', views.GateListView.as_view(gate_type='ikw'), name='ikw_list'),
    url(r'^ikk$', views.GateListView.as_view(gate_type='ikk'), name='ikk_list'),
    url(r'^(?P<pk>[\w-]+)/$', views.DetailView.as_view(), name='gate_details'),
    url(r'^(?P<pk>[\w-]+)/update$', views.gate_update, name='update'),
    url(r'^(?P<pk>[\w-]+)/log$', views.LogView.as_view(), name='log'),
    url(r'^add$', views.gate_add, name='gate_add'),
    url(r'^(?P<pk>[\w-]+)/edit$', views.gate_edit, name='edit'),
    url(r'^mygates$', views.MyGates.as_view(), name='my_gates'),
    url(r'^massupdate$', views.mass_update, name='mass_update'),
    url(
        r'^csm/(?P<car>\D\d)/(?P<operation_no>\D{2}\d{4})$',
        views.gate_change_status_mobile,
        name='gate_change_status_mobile'
    )

]

qapp/models.py
import os
import uuid
import ntpath
from datetime import date
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.deconstruct import deconstructible
from django.core.validators import MinValueValidator, MaxValueValidator


@deconstructible
class UploadToPathAndRename(object):

    # Custom path and filename for uploaded files; code found on stackoverflow and edited.

    def __init__(self, path):
        self.sub_path = path

    def __call__(self, instance, filename):
        comm_pk = instance.file_rel_comment.pk
        org_filename = filename.split('.')[:-1]
        ext = filename.split('.')[-1]
        filename = '{}_{}.{}'.format(comm_pk, org_filename, ext)
        # return the whole path to the file
        return os.path.join(self.sub_path, filename)


class Tram(models.Model):
    number = models.CharField(max_length=3)
    manufactured_date = models.IntegerField(default=date.today().year, validators=[
        MinValueValidator(2017),
        MaxValueValidator(date.today().year)
    ]
                                           )
    objects = models.Manager

    class Meta:
        ordering = ('-number',)

    def __str__(self):
        return self.number


class Bogie(models.Model):

    BOGIE_TYPES = (
        ('WN1', u'Wózek napędowy 1'),
        ('WN2', u'Wózek napędowy 2'),
        ('WT', u'Wózek toczny'),
        ('WN3', u'Wózek napędowy 3'),
        ('WN4', u'Wózek napędowy 4'),
    )

    number = models.CharField(max_length=11)
    manufactured_date = models.IntegerField(default=date.today().year, validators=[
        MinValueValidator(2017),
        MaxValueValidator(date.today().year)
    ]
                                           )
    btype = models.CharField(choices=BOGIE_TYPES, null=True, max_length=3, verbose_name='Bogie type')
    objects = models.Manager

    class Meta:
        ordering = ('-number',)

    def __str__(self):
        return '{} ({})'.format(self.number, self.btype)


class OperationArea(models.Model):

    AREAS = (
        ('KLE', u'Klejownia'),
        ('KAB', u'Kablownia'),
        ('PDM', u'Podmontaż dachów - mechanika'),
        ('PDE', u'Podmontaż dachów - elektryka'),
        ('MGM', u'Montaż główny - mechanika'),
        ('MGE', u'Montaż główny - elektryka'),
        ('MKM', u'Montaż końcowy - mechanika'),
        ('MKE', u'Montaż końcowy - elektryka'),
        ('MWM', u'Montaż wózków - mechanika'),
        ('MWE', u'Montaż wózków - elektryka'),
        ('MKA', u'Montaż kabin'),
        ('TES', u'Testing'),
        ('MWM', u'Montaż wózków - mechanika'),
        ('MWE', u'Montaż wózków - elektryka'),
        ('IWD', u'Inspekcja końcowa wewnętrzna - dach'),
        ('IWP', u'Inspekcja końcowa wewnętrzna - podwozie'),
        ('IWW', u'Inspekcja końcowa wewnętrzna - wnętrzne'),
        ('IWZ', u'Inspekcja końcowa wewnętrzna - zewnątrz'),
        ('IWL', u'Inspekcja końcowa wewnętrzna - lakier'),
        ('IKT', u'Inspekcja końcowa klienta - tramwaj')
    )

    area = models.CharField(choices=AREAS, max_length=3)
    foreman = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    objects = models.Manager

    def __str__(self):
        return self.area


class Gate(models.Model):

    GATE_TYPE = (
        ('BJC', u'Bramka jakościowa - człon'),
        ('BJW', u'Bramka jakościowa - wózek'),
        ('IKW', u'Inspekcja końcowa - wewnętrzna'),
        ('IKK', u'Inspekcja końcowa - klient'),
    )

    CAR_SYMBOLS = (
        ('C1', u'C1'),
        ('C2', u'C2'),
        ('C3', u'C3'),
        ('C4', u'C4')
    )

    GATE_STATUSES = (
        ('R', u'Realizacja'),
        ('O', u'Ocena DZJ'),
        ('P', u'Ponowna realizacja'),
        ('A', u'Archiwum')
    )

    GATE_GRADES = (
        ('OK', u'Zaakceptowany'),
        ('NOK', u'Odrzucony')
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    type = models.CharField(choices=GATE_TYPE, default='BJC', max_length=3)
    tram = models.ForeignKey(Tram, null=True, blank=True, on_delete=models.CASCADE)
    bogie = models.ForeignKey(Bogie, null=True, blank=True, on_delete=models.CASCADE)
    car = models.CharField(choices=CAR_SYMBOLS, max_length=2, null=True, blank=True,)
    area = models.ForeignKey(OperationArea, null=True, on_delete=models.CASCADE)
    responsible = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    operation_no = models.CharField(max_length=6, null=True)
    name = models.CharField(max_length=200)
    content = models.TextField()
    status = models.CharField(choices=GATE_STATUSES, default='R', max_length=1)
    rating = models.CharField(choices=GATE_GRADES, blank=True, max_length=3)
    reject_counter = models.IntegerField(default='0')
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='author')
    creation_date = models.DateTimeField(default=timezone.now)
    modify_date = models.DateTimeField(default='', blank=True, null=True)
    # Without this, call gate.object was impossible
    objects = models.Manager

    class Meta:
        ordering = ('-tram',)
        permissions = (
            ('can_change_gate_status', u'Może zmenić status bramki'),
            ('can_change_gate_rating', u'Może zmienić ocenę bramki'),
            ('can_add_new_gate', u'Może dodać nową bramkę')
        )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('qapp:gate_details', args=[
            self.pk,
        ])


class GateFile(models.Model):
    file_rel_gate = models.ForeignKey(Gate, on_delete=models.CASCADE)
    file = models.FileField(upload_to='uploads_g', blank=True, null=True)

    def filename(self):
        return ntpath.basename(self.file.name)

    def __str__(self):
        return 'Załącznik do bramki: {}'.format(str(self.file)[10:])


class Comment(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    com_rel_gate = models.ForeignKey(Gate, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    text = models.TextField(max_length=2000, blank=True, null=True)
    date_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return 'Komentarz, autor: {}'.format(self.author)


class CommentFile(models.Model):
    file_rel_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    file = models.FileField(upload_to=UploadToPathAndRename(os.path.join('uploads_c')), blank=True, null=True)

    def filename(self):
        return ntpath.basename(self.file.name)

    def __str__(self):
        return 'Załącznik do komentarza: {}'.format(str(self.file)[10:])


class Log(models.Model):

    log_rel_gate = models.ForeignKey(Gate, on_delete=models.CASCADE)
    date_time = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    category = models.CharField(max_length=1, blank=True)
    action = models.CharField(max_length=30)

    def __str__(self):
        return 'Log z {}'.format(self.date_time)

qapp/templates/qapp/gate/details.html
{% extends 'qapp/base.html' %}
{% load user_tags %}

{% block title %}QAPP - {{ gate.name }} - szczegóły{% endblock %}

{% block content %}
<div class="card" id="gate_{{ gate.id}}_details">
    <table class="wp-table">
        <tr>
            <th class="field-header">Pole</th>
            <th>Wartość</th>
        </tr>
        <tr>
            <td>Typ:</td>
            <td>{{ gate.get_type_display }}</td>
        </tr>
        {% if gate.type == 'BJW' %}
        <tr>
            <td>Wózek:</td>
            <td>{{ gate.bogie }}</td>
        </tr>
        <tr>
            <td>Typ wózka:</td>
            <td>{{ gate.bogie.btype }}</td>
        </tr>
        {% else %}
        <tr>
            <td>Numer tramwaju:</td>
            <td>{{ gate.tram }}</td>
        </tr>
        <tr>
            <td>Człon:</td>
            <td>{{ gate.car }}</td>
        </tr>
        {% endif %}
        <tr>
            <td>Obszar:</td>
            <td>{{ gate.area }} ({{ gate.area.get_area_display }})</td>
        </tr>
        <tr>
            <td>Odpowiedzialny:</td>
            <td>{{ gate.responsible.last_name }} {{ gate.responsible.first_name }} ({{ gate.responsible }})</td>
        </tr>

        {% if gate.type == 'BJW' or gate.type == 'BJC' %}
        <tr>
            <td>Numer operacji:</td>
            <td>{{ gate.operation_no }}</td>
        </tr>
        {% endif %}
        <tr>
            <td>Nazwa:</td>
            <td>{{ gate.name }}</td>
        </tr>
        <tr>
            <td>Wytyczne</td>
            <td>{{ gate.content | linebreaks }}</td>
        </tr>
        <tr>
            <td>Data utworzenia:</td>
            <td>{{ gate.creation_date|date:"Y-m-d H:i:s.u" }}<br>
            (ostatnia zmiana: {% if gate.modify_date != None %} {{ gate.modify_date|date:"Y-m-d H:i:s.u" }} {% else %} nigdy {% endif %})</td>
        </tr>
        <tr>
            <td>Dodatkowe pliki:</td>
            <td>
                {% if gate.gatefile_set.all %}
                {% for document in gate.gatefile_set.all %}
                <div class="file">
                    <a class="filelink" href="{{ document.file.url }}" target="_blank">{{ document.filename }}</a><br>
                </div>
                {% endfor %}
                {% else %}
                Brak dodatkowych plików
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>Status realizacji:</td>
            <td>{{ gate.get_status_display }} ({{ gate.status }})</td>
        </tr>
        <tr>
            <td>Ilość odrzuceń:</td>
            <td>{{ gate.reject_counter }}</td>
        </tr>
        <tr>
            <td>Ocena</td>
            <td>{{ gate.get_rating_display|default:"---" }} {% if gate.rating %} ({{ gate.rating }}) {% endif %}</td>
        </tr>
    </table>
    <br>
</div>
<div class="card" id="gate_{{ gate.id}}_form">
    <form action="{% url 'qapp:update' gate.pk %}" method="post" enctype="multipart/form-data" onsubmit="return ValidateForm();">
        {% csrf_token %}
        {% if gate.status == 'A' %}
        Nie masz uprawnień do wykonywania akcji dla tej bramki.
        {% elif request.user == gate.responsible and gate.status == 'O' %}
        W oczekiwaniu na ocenę DZJ nie możesz wykonywać żadnych akcji.
        {% elif request.user|dzj_member or request.user == gate.responsible and gate.status != 'A' %}
        {% for field in comment_form %}
        {{ field.label_tag }}
        <br>
        {% if field.errors %}<font color="red">{{ field.errors }}{% endif %}{{ field }}</font>
        <br>
        {% endfor %}
        {{ comment_formset.management_form }}
        Dodaj opcjonalne pliki:
        <br>
        (aby zresetować formularz, odśwież stronę)
        <br>
        <div class="upload-buttons-area" id="upload_buttons_area">
        {% for form in comment_formset %}
        {% for field in form.visible_fields %}
            <label class="upload-button" id="label_{{ field.auto_id }}">
            Wybierz plik!{% if field.errors %}<font color="red">{{ field.errors }}{% endif %}{{ field }}</font>
            </label>
        {% endfor %}
        {% endfor %}
        </div>
        <div class="action-buttons-area" id="action_buttons_area">
        {% if gate.status == 'R' or gate.status == 'P' %}
        <button class="status-button" name="new_status" type="submit" value="O">Wyślij do akceptacji DZJ</button>
        {% endif %}
        {% if request.user|dzj_member and gate.status == 'O' %}
        <div id="fastaction">
            <button name="new_rating" type="submit" value="OK" class="ok-button-long">Akceptuj</button>
            <button name="new_rating" type="submit" value="NOK" class="nok-button-long">Odrzuć</button>
        </div>
        <button class="ok-button" name="new_rating" type="submit" value="OK">Akceptuj</button>
        <button class="nok-button" name="new_rating" type="submit" value="NOK">Odrzuć</button>
        {% endif %}
        </div>
        {% else %}
        Nie masz uprawnień do wykonywania akcji dla tej bramki.
        {% endif %}
    </form>
    <br>
    <div id="canvas-area" style="overflow: hidden; height: 0;"></div>
</div>
{% for comment in gate.comment_set.all reversed %}
<div class="card" id="gate_{{ gate.id}}_comment_{{ comment.id }}">
    <p><b>Autor: </b>{{ comment.author.first_name }} {{ comment.author.last_name}} ({{ comment.author }}), {{ comment.date_time|date:"Y-d-m, H:i:s" }}</p>
    <p><b>Treść: </b>{{ comment.text }}</p>
    {% for document in comment.commentfile_set.all %}
    <p><b>Plik: </b><a href="{{ document.file.url }}" target="_blank">{{ document.filename }}</a></p>
    {% endfor %}
    <p><i><font color="#DDDDDD">Id komentarza: {{ comment.id }}</font></i></p>
</div>
{% endfor %}
{% endblock %}

{% block firstcard %}
<h3>Szybkie akcje:</h3>
<hr>
<ul>
    <li><a href="{{ request.META.HTTP_REFERER }}">Wróć do poprzedniego widoku</a></li>
    {% if gate.type == 'BJW' %}
    <li><a href="{% url 'qapp:bjw_list' %}?bogie={{ gate.bogie.pk }}&bogie_type={{ gate.bogie_type }}&area={{ gate.area.pk }}">Zobacz inne bramki z obszaru {{ gate.area }} na wózku {{ gate.bogie }} typ {{ gate.bogie_type }}</a></li>
    {% else %}
    <li><a href="{% url 'qapp:index' %}{{ gate.type|lower }}?tram={{ gate.tram.pk }}&car={{ gate.car }}&area={{ gate.area.pk }}">Zobacz inne bramki z obszaru {{ gate.area }} na pojeździe {{ gate.tram }} człon {{ gate.car }}</a></li>
    {% endif %}
    <li><a href="{% url 'qapp:log' gate.pk %}" target="_blank">Zobacz log</a></li>
    {% if request.user|dzj_member %}
    <li><a href="{% url 'qapp:edit' gate.pk %}">Edytuj</a></li>
    {% endif %}
    <li><a href="#">Skontaktuj się z autorem: {{ gate.author }}</a></li>
</ul>
{% endblock %}

qapp/templates/qapp/gate/index.html
{% extends 'qapp/base.html' %}

{% block title %}QAPP - strona główna{% endblock%}

{% block content %}
    <div class="card" id="index">
        <h1>Wybierz moduł:</h1>
        <a href="{% url 'qapp:bjc_list' %}" class="index-button">Bramki jakościowe - człony</a>
        <a href="{% url 'qapp:bjw_list' %}" class="index-button">Bramki jakościowe - wózki</a>
        <a href="{% url 'qapp:ikw_list' %}" class="index-button">Inspekcja końcowa - wewnętrzna</a>
        <a href="{% url 'qapp:ikk_list' %}" class="index-button">Inspekcja końcowa - klient</a>
    </div>
{% endblock %}

{% block firstcard %}
    <h3>Informacje o użytkowniku</h3>
    <hr>
    {% if user.is_authenticated %}
    Zalogowany użytkownik: <b>{{ user }}</b>
    <br>
    <br>
    Należy do grupy:
    {% for group in user.groups.all %}
    <b>{{ group|upper }},</b>
    {% endfor %}
    {% else %}
    Treść dostępna tylko dla zalogowanych użytkowników!
    {% endif %}
{% endblock %}

qapp/templates/qapp/gate/list.html
{% extends 'qapp/base.html' %}
{% load user_tags %}

{% block title %}QAPP - lista bramek{% endblock%}

{% block content %}
<div class="card" id="gate_{{ gate_type }}_list">
    {% if user.is_authenticated and request.user|dzj_member %}
    <form action="{% url 'qapp:mass_update' %}" method="post">
        {% csrf_token %}
        <div id="fastaction">
            <button name="new_rating" type="submit" value="OK" class="ok-button-long">Akceptuj</button>
            <button name="new_rating" type="submit" value="NOK" class="nok-button-long">Odrzuć</button>
        </div>
    {% endif %}
        <table class="wp-table">
            <tr>
                {% if 'bjw' in gate_type %}
                <th><div class="rotated">Wózek</div></th>
                {% else %}
                <th><div class="rotated">Tramwaj</div></th>
                <th><div class="rotated">Człon</div></th>
                {% endif %}
                <th><div class="rotated">Obszar</div></th>
                <th><div class="rotated">Numer operacji</div></th>
                <th><div class="rotated">Nazwa</div></th>
                <th><div class="rotated">Status</div></th>
                <th><div class="rotated">Ocena</div></th>
                <th><div class="rotated">Zaznacz</div></th>
            </tr>
            {% for gate in gate_list %}
            <tr class="clickable" id="gate_{{ gate.id }}">
                {% if 'bjw' in gate_type %}
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.bogie }}</a></td>
                {% else %}
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.tram }}</a></td>
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.car }}</a></td>
                {% endif %}
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.area }}</a></td>
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.operation_no }}</a></td>
                <td class="gate-name"><a href="{{ gate.get_absolute_url }}">{{ gate.name }}</a></td>
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.status }}</a></td>
                <td><a href="{{ gate.get_absolute_url }}">{{ gate.rating|default:"---" }}</a></td>
                <td class="center">
                    <label for="{{ gate.id }}">
                        <div class="checkbox-area">
                            <input type="checkbox" id="{{ gate.id }}" name="{{ gate.id }}">
                        </div>
                    </label>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% if user.is_authenticated and request.user|dzj_member %}
    </form>
    {% endif %}
    {% if is_paginated %}
    <div class="pagination" align="center">
        <br>
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="/qapp/{{ gate_type }}?{% param_replace page=page_obj.previous_page_number %}">poprzednia</a>
            {% else %}
            <a><font color="#CCC9C9">poprzednia</font></a>
            {% endif %}
            <span class="page-current">|  Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}  |</span>
            {% if page_obj.has_next %}
            <a href="/qapp/{{ gate_type }}?{% param_replace page=page_obj.next_page_number %}">następna</a>
            {% else %}
            <a><font color="#CCC9C9">nastepna</font></a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block firstcard %}
<h3>Filtrowanie</h3>
<hr>
{% if user.is_authenticated %}
<form method="get">
    <table>
        <tr>
        {% for field in gate_list_filter.form %}
        {% if 'bjw' in gate_type %}
        {% if 'tram' not in field.name and 'car' not in field.name %}
            <td>{{ field.label_tag}}</td>
            <td>{{ field }}</td>
        {% endif %}
        {% else %}
        {% if 'bogie' not in field.name %}
            <td>{{ field.label_tag}}</td>
            <td>{{ field }}</td>
        {% endif %}
        {% endif %}
        </tr>
        {% endfor %}
    </table>
    <hr>
    <button type="submit" class="standard-button">Filtruj</button>
    <button type="button" class="standard-button" onclick="location.href='{{ request.path }}'">Resetuj</button>
</form>
{% else %}
Filtrowanie dostępne tylko dla zalogowanych użytkowników!
{% endif %}
{% endblock %}

qapp/templates/qapp/gate/log.html
{% extends 'qapp/base.html' %}

{% block title %}QAPP - {{ gate.name }} - log{% endblock %}

{% block content %}
<div class="card" id="gate_{{ gate.id }}_log">
    LOG:
    <br>
    <br>
    {% for log in gate.log_set.all reversed %}
    {% if log.category == 'E' %}
    <p class="error">{{ log.date_time|date:"Y-m-d H:i:s.u" }}: użytkownik <b>{{ log.author }}</b> wykonał akcję <b>{{ log.action }} (BŁĄD)</b></p>
    {% else %}
    <p>{{ log.date_time|date:"Y-m-d H:i:s.u" }}: użytkownik <b>{{ log.author }}</b> wykonał akcję <b>{{ log.action }}</b></p>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

qapp/templates/qapp/gate/mygates.html
{% extends 'qapp/base.html' %}
{% load user_tags %}
{% load static %}

{% block title %}QAPP - moje bramki{% endblock%}

{% block content %}
<div class="card" id="my_gates">
    <table class="wp-table">
        <tr>
            <th>Typ</th>
            <th>Tramwaj</th>
            <th>Człon</th>
            <th>Wózek</th>
            <th>Obszar</th>
            <th>Numer operacji</th>
            <th>Nazwa</th>
            <th>Autor</th>
            <th>Odpowiedzialny</th>
            <th>Status</th>
            <th>Ocena</th>
            {% if request.user|dzj_member %}
            <th>Edytuj</th>
            {% endif %}
        </tr>
        {% for gate in user_gates %}
        <tr class="clickable" id="gate_{{ gate.id }}">
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.type }}</a></td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.tram|default_if_none:"-----" }}</a></td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.car|default_if_none:"-----" }}</a></td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.bogie|default_if_none:"-----" }}</a></td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.area }}</a></td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.operation_no|default_if_none:"-----" }}</a></td>
            <td class="gate-name"><a href="{{ gate.get_absolute_url }}">{{ gate.name }}</a></td>
            <td>
                <a href="{{ gate.get_absolute_url }}">
                    {{ gate.author.last_name }} {{ gate.author.last_name }} ({{ gate.author.username }})
                </a>
            </td>
            <td>
                <a href="{{ gate.get_absolute_url }}">
                    {{ gate.responsible.last_name }} {{ gate.responsible.first_name }} ({{ gate.responsible }})
                </a>
            </td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.get_status_display }}</a></td>
            <td><a href="{{ gate.get_absolute_url }}">{{ gate.rating|default:"---" }}</a></td>
            {% if request.user|dzj_member %}
            <td class="center"><a href="{% url 'qapp:edit' gate.pk %}"><img src="{% static 'img/edit.png' %}"></a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
    <div class="pagination" align="center">
        <br>
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="/qapp/mygates?{% param_replace page=page_obj.previous_page_number %}">poprzednia</a>
            {% else %}
            <a><font color="#CCC9C9">poprzednia</font></a>
            {% endif %}
            <span class="page-current">|  Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}  |</span>
            {% if page_obj.has_next %}
            <a href="/qapp/mygates?{% param_replace page=page_obj.next_page_number %}">następna</a>
            {% else %}
            <a><font color="#CCC9C9">nastepna</font></a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block firstcard %}
<h3>Filtrowanie</h3>
<hr>
{% if user.is_authenticated %}
<form method="get">
    <table>
        {% for field in user_gates_filter.form %}
        {% if not 'area' in field.name %}
        <tr>
            <td>{{ field.label_tag}}</td>
            <td>{{ field }}</td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>
    <hr>
    <button type="submit">Filtruj</button>
    <button onclick="location.href='{% url 'qapp:my_gates' %}'" type="button">Resetuj</button>
</form>
{% else %}
Filtrowanie dostępne tylko dla zalogowanych użytkowników!
{% endif %}
{% endblock %}